config/routes.rb
Rails.application.routes.draw do
  resources 'machines'

  resources 'tijds'

  get 'machines/index'
  get 'machines/show'
end

app/models/machine.rb
class Machine < ActiveRecord::Base
	has_many :tijds
end

app/models/tijd.rb
class Tijd < ActiveRecord::Base
	belongs_to :machine

	def self.delete_run_innings
		@tijd_nu = Time.now
		@tijd_nu = @tijd_nu.strftime("%d/%m/%Y %H:%M")
		tijds = Tijd.where('end_datetime < ?', @tijd_nu)

		tijds.each do |tijd|
			tijd.destroy
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController

	def index
		@machines = Machine.all()
	end

	def new
		@machine = Machine.new()
	end

	def show
	end

	def edit
		@machine = Machine.find(params[:id])
	end

	def destroy
		@machine = Machine.find(params[:id])
		@machine.destroy
	end

	def update
		@machine = Machine.find(params[:id])

		if @machine.update(machine_params)
			redirect_to @machine
		else
			render 'edit'
		end
	end

	def create
		@machine = Machine.new(machine_params)
		if @machine.save
			redirect_to @machine
		else
			render 'new'
		end
	end

	private
  	def machine_params
  		params.require(:machine).permit(:kind, :name)
  	end
end

app/controllers/tijds_controller.rb
class TijdsController < ApplicationController

	def create
	  	@tijd = Tijd.new(tijd_params)

	  	@tijd_nu = Time.now
	  	@tijd_nu.strftime("%d/%m/%Y %H:%M")

	  	ingevulde_tijd = params[:tijd][:end_datetime]
	  	ingevulde_tijd = ingevulde_tijd.to_i

	  	@uiteindelijke_tijd = @tijd_nu + ingevulde_tijd.minutes
	  	@uiteindelijke_tijd = @uiteindelijke_tijd.strftime("%d/%m/%Y %H:%M")
	  	@tijd.end_datetime = @uiteindelijke_tijd

	  	if @tijd.save
	  		redirect_to tijds_path
	  	end
	end

	def index
		@tijds = Tijd.all()
	end

	def show
	end

	def new
		@tijd = Tijd.new()
	end

	private
  	def tijd_params
  		params.require(:tijd).permit(:end_datetime, :machine_id)
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/helpers/tijds_helper.rb
module TijdsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WasApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/machines/edit.html.erb
<h1>Machines toevoegen</h1>

<%= form_for :machine, url: machine_path(@machine), method: :patch do |f| %>
	<%= label_tag(:kind, "Type:") %><br />
	<%= f.text_field :kind %>
	<br /><br />

	<%= label_tag(:machine_id, "Beschrijving:") %><br />
	<%= f.integer :machine_id, size: "50x10" %>
	<br /><br />

	<%= label_tag(:url, "URL:") %><br />
	<%= f.text_field :url %>
	<br /><br />

	<%= f.submit "Aanmaken" %>

<% end %>

app/views/machines/index.html.erb
<%= link_to 'Nieuwe aanmaken', new_machine_path %><br />
<br /><br />

<% @machines.each do |machine| %>
<b><%= machine.name %></b><br/>
<% end %>

app/views/machines/new.html.erb
<%= form_for @machine, url: {action:"create"}, multipart: true do |f| %>
	<%= label_tag(:kind, "Type:") %><br />
	<%= f.number_field :kind %>
	<br /><br />

	<%= label_tag(:name, "Naam:") %><br />
	<%= f.text_field :name %>
	<br /><br />	

	<%= f.submit "Aanmaken" %>
<% end %>

app/views/tijds/index.html.erb
<h1>Ingevoerde wasbeurten</h1>

<%= link_to 'Nieuwe aanmaken', new_tijd_path %><br /><br /><br />

	<% @tijds.each do |tijd| %>
		<% if tijd.machine.name %>
			<b><%= tijd.machine.name %></b>
		<% end %>
		<i><%= tijd.end_datetime %></i><br /><br />
	<% end %>

app/views/tijds/new.html.erb
<h1>Items#new</h1>

<%= form_for @tijd, url: {action:"create"}, multipart: true do |f| %>

	<%= label_tag(:machine_id, "Machine:") %><br />
	<%= f.collection_select :machine_id, Machine.all, :id, :name %>

	<br /><br />

	<%= label_tag(:end_datetime, "Duur van je wasbeurt: (in minuten)") %><br />
	<%= f.time_field :end_datetime %>

	<br /><br />

	<%= f.submit "Reserveren" %>

<% end %>